### ISSUE TITLE
[Lab2] ερωτημα 2.3 

### ISSUE THREAD

**Issue by filippasoumpasakou** [ntua-cvsp-lab/DSP_LabSupport#51]
Καλησπέρα, 
Σε αυτο το ερωτημα ζητείται η συναρτηση **gaborfilt(signal, fc, α, fs)** να υλοποιεί όλο το filterband ή ενα φιλτρο σε συγκεκριμενη κεντρικη συχνοτητα fc; (δηλαδη εκτος συναρτησης να τα σχεδιασουμε ολα αλλαζοντας την κεντρικη συχνοτητα)

**Comment by cgaroufis** [comment]
Καλησπέρα,

Και τα δύο που προτείνεις είναι ορθά - ο ορισμός των κεντρικών συχνοτήτων πρέπει να γίνει εκτός συνάρτησης. Από εκεί και πέρα, το αν θα καλείτε τη συνάρτηση ξεχωριστά για την κάθε κεντρική συχνότητα (με ένα for loop στον κώδικα πχ) ή θα την καλείτε χρησιμοποιώντας ένα διάνυσμα από κεντρικές συχνότητες φίλτρων fc, στην οποία περίπτωση η συνάρτηση θα επιστρέφει έναν 2D array απο φιλτραρισμένα σήματα, αφήνεται σε εσάς - αν και το πρώτο είναι "ορθότερο" διαισθητικά.

Καλή συνέχεια,
Χρήστος
