### ISSUE TITLE
[Lab2] 2.7d) Σχεδίαση Γραφικής Παράστασης

### ISSUE THREAD

**Issue by odychlapanis** [ntua-cvsp-lab/DSP_LabSupport#72]
Καλησπέρα,
Στο ερώτημα 2.7δ έχω φτιάξει έναν πίνακα ΜΤΕ μίας διάστασης (με 119 στοιχεία όσα και τα παράθυρα) που περιέχει τις μέσες τιμές της Teager Ενέργειας. Έχω φτιάξει και έναν άλλο πίνακα δύο διαστάσεων όπου στη μία διάσταση έχει τον αριθμό των παραθύρων μου (119) και στην άλλη τον αριθμό των δειγμάτων του ενός παραθύρου. Ο δεύτερος πίνακας περιέχει την έξοδο των φίλτρων που είχαν τη μέγιστη μέση τιμή Teager Ενέργειας. Κανέναν από τους τρεις πίνακες όμως δεν μπορώ να τους σχεδιάσω επειδή ο ένας είναι διακριτό σήμα που παίρνει μόνο 119 τιμές και ο άλλος παίρνει πολύ περισσότερες τιμές από ότι το σήμα μου επειδή τα παράθυρα έχουν επικάλυψη. Τι πρέπει λοιπόν να κάνω;

**Comment by cgaroufis** [comment]
Καλημέρα,

Για τον πρώτο πίνακα (που είναι και αυτός που ζητείται να σχεδιαστεί στην άσκηση), μπορείς να κάνεις τα εξής:
α) Να τον επαναδειγματοληπτήσεις, ώστε να αποκτήσει το ίδιο μήκος με το αρχικό σήμα σου (είτε με χρήση της resample της scipy είτε μέσω γραμμικής παρεμβολής)
β) Να ορίσεις ένα linspace για το κάθε σήμα σου, ορισμένα στον ίδιο χώρο (πχ seconds αφού αντιστοιχούν στο ίδιο χρονικό διάστημα) και το καθένα με αριθμό στοιχείων ίσο με τον αριθμό δειγμάτων του αντίστοιχου σήματος. Έπειτα, να τα περάσεις σαν x-αξονες όταν θα καλείς την plot() για το αντιστοιχο σήμα κάθε φορά.

Για το δεύτερο σήμα που λες, δε ζητείται από την άσκηση η γραφική του παράσταση. Πάντως η διαδικασία που ακολουθείται σε αυτές τις περιπτώσεις (όπου πρέπει να ανακατασκευάσεις ένα σήμα από επικαλυπτόμενα παραθυρωμένα τμήματα) είναι γνωστή ως μέθοδος [overlap-add](https://ccrma.stanford.edu/~jos/sasp/Overlap_Add_Decomposition.html). Συνοπτικά, αυτό που κάνεις είναι να αρχικοποιείς ένα μηδενικό διάνυσμα, και στη συνέχεια να προσθέτεις το κάθε παράθυρωμένο πλαίσιο στη θέση που του αντιστοιχεί. Έπειτα, αν τα παράθυρα που χρησιμοποιείς (πχ Hamming, Bartlett...) ικανοποιούν (προσεγγιστικά) τη συνθήκη σταθερού αθροίσματος (βλ σχήμα), 

![cola](https://user-images.githubusercontent.com/25747664/83734473-ba870d80-a657-11ea-9a6b-57cd09d6969f.png)

μπορείς απλά να πάρεις το τελικό σου σήμα διαιρώντας με το άθροισμα αυτό.

Kαλή συνέχεια,
Χρήστος
