### ISSUE TITLE
[Lab2] 3.3 Συνθήκη τερματισμού

### ISSUE THREAD

**Issue by odychlapanis** [ntua-cvsp-lab/DSP_LabSupport#77]
Γεια σας και πάλι,
Υποθέτοντας ότι τα προηγούμενα που είχα κάνει είναι σωστά, προχώρησα στο επόμενο ερώτημα. Δεν έχω καταλάβει καλά ποια είναι η συνθήκη τερματισμού του Κ-means. Είναι όταν Distortion[n]=Distortion[n-1]-N, όπου Ν μεγάλος ακέραιος ή Distortion[n]=Distortion[n-1]//N ή κάτι άλλο? Επίσης πόσο χρόνο να αναμένουμε περίπου ότι θα πάρει ο Κ-means? Περίπου 10 λεπτά ας πούμε ή κάτι σαν μισή ώρα και παραπάνω?

**Comment by EvansManGR** [comment]
Αρχικά να πω ότι εμένα προσωπικά τρέχει για λιγότερο από 10 κύκλους για να βρει τα σωστά "κέντρα". Αν βάλεις να σου τυπώνει τα "κέντρα" που βρίσκει κάθε φορά, θα δεις ότι είναι τα ίδια από ένα σημείο και μετά.

Τώρα για τη συνθήκη τερματισμού, κάτι σε μπέρδεψε. Θα πρέπει να συγκρίνεις την ολική παραμόρφωση για τα τελευταία "κέντρα" που βρήκες, με την ολική παραμόρφωση για τα  κέντρα που είχες στον προηγούμενο κύκλο του βρόχου σου. 
Δλδ previous_D - current_D < [έναν πολύ μικρό αριθμό]

Όπου "ολική παραμόρφωση" είναι το άθροισμα των  -ευκλείδειων- αποστάσεων του κάθε σημείου από το κέντρο του, για όλα τα σημεία(άσχετα από την κλάση στην οποία ανήκουν).

Ουσιαστικά ο αλγόριθμος θέλει να πετύχει την συνολικά μικρότερη δυνατή απόσταση του κάθε σημείου από το κοντινότερο κέντρο του.

Ελπίζω να βοήθησα και να μη σε μπέρδεψα παραπάνω.
Βαγγέλης

**Comment by odychlapanis** [comment]
Ευχαριστώ Βαγγέλη!

**Comment by filby89** [comment]
Επιβεβαιώνω και γώ ότι η διαδικασία που περιέγραψε ο Βαγγέλης είναι σωστή!
